"""Make SKU nullable and remove unique constraint

Revision ID: 145b9dcf0efb
Revises: 16f9d3ae46cf
Create Date: 2026-02-19 09:02:29.969736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145b9dcf0efb'
down_revision = '16f9d3ae46cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=1)

    # ### end Alembic commands ###
