"""Add payment_method to Sales

Revision ID: 16f9d3ae46cf
Revises: 
Create Date: 2026-02-19 08:45:59.551381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f9d3ae46cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False, server_default='efectivo'))
    
    # Actualizar columna después de agregar con default
    op.execute("UPDATE sale SET payment_method = 'efectivo' WHERE payment_method IS NULL OR payment_method = ''")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
