"""add payment tracking to sales

Revision ID: a156297d37c5
Revises: 145b9dcf0efb
Create Date: 2026-02-19 09:26:55.221584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a156297d37c5'
down_revision = '145b9dcf0efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_cents', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='pagado'))

    # Actualizar ventas existentes
    connection = op.get_bind()
    
    # Para ventas que NO son fiado, marcarlas como pagadas completamente
    connection.execute(sa.text("""
        UPDATE sale 
        SET paid_cents = total_cents, 
            payment_status = 'pagado' 
        WHERE payment_method != 'fiado' OR payment_method IS NULL
    """))
    
    # Para ventas fiadas, marcarlas como pendientes con paid_cents = 0
    connection.execute(sa.text("""
        UPDATE sale 
        SET paid_cents = 0, 
            payment_status = 'pendiente' 
        WHERE payment_method = 'fiado'
    """))
    
    # Remover server_default después de la actualización
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('paid_cents', server_default=None)
        batch_op.alter_column('payment_status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('paid_cents')

    op.drop_table('payment')
    # ### end Alembic commands ###
