"""add minimum_stock to products

Revision ID: add_minimum_stock
Revises: add_user_id_multi_user
Create Date: 2026-03-02 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_minimum_stock'
down_revision = 'add_user_id_multi_user'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('minimum_stock', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'minimum_stock')
    # ### end Alembic commands ###
