"""Add role-based permissions to settings

Revision ID: ec6c9ecfe7a5
Revises: 8b3776d702b7
Create Date: 2026-03-02 02:41:11.391407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6c9ecfe7a5'
down_revision = '8b3776d702b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_permissions', sa.String(length=500), nullable=False, server_default='{"dashboard":true,"products":true,"sales":true,"debts":true,"reports":true,"users":true,"settings":true}'))
        batch_op.add_column(sa.Column('gerente_permissions', sa.String(length=500), nullable=False, server_default='{"dashboard":true,"products":true,"sales":true,"debts":true,"reports":true,"users":false,"settings":false}'))
        batch_op.add_column(sa.Column('vendedor_permissions', sa.String(length=500), nullable=False, server_default='{"dashboard":false,"products":true,"sales":true,"debts":false,"reports":false,"users":false,"settings":false}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('vendedor_permissions')
        batch_op.drop_column('gerente_permissions')
        batch_op.drop_column('admin_permissions')

    # ### end Alembic commands ###
